service: kendrabackend

provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
  stage: dev
  region: us-east-1
  memorySize: 128

custom:
  lambda_admin: "arn:aws:iam::134588522078:role/lambda_admin"
  kendra_index_id : "61f14cdb-319a-4f91-87e8-087508f57895"
  user_pool_arn : "arn:aws:cognito-idp:us-east-1:134588522078:userpool/us-east-1_23Z2YmLff"

# you can add packaging information here 
package:
  individually: true
  exclude:
    - ./**

functions:
  kendraTest:
    handler: handler.hello
    package:
      include:
        - ./handler.py
    events:
      - http:
          path: /kendratest
          method: get
  kendraQuery:
    role: ${self:custom.lambda_admin}
    environment:
      INDEX_ID: ${self:custom.kendra_index_id}
    handler: kendraQuery.handler
    package:
      include:
        - ./kendraQuery.py
    events:
      - http:
          path: /kendraquery
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.user_pool_arn}

